# -*- coding: utf-8 -*-


class DeptAssoc:
    """
    Desc: 组织关联信息
    Author: David
    Date: 2020/12/11
    """

    def __init__(self, **kwargs):
        self.tenant_id = kwargs.get('tenant_id', 0)
        self.dept_code = kwargs.get('hhr_dept_code', '')
        self.efft_date = kwargs.get('hhr_efft_date', None)
        self.efft_end_date = kwargs.get('hhr_hhr_efft_end_date', None)
        self.dept_list01 = kwargs.get('hhr_dept_list01', '')
        self.dept_list02 = kwargs.get('hhr_dept_list02', '')
        self.dept_list03 = kwargs.get('hhr_dept_list03', '')
        self.dept_list04 = kwargs.get('hhr_dept_list04', '')
        self.dept_list05 = kwargs.get('hhr_dept_list05', '')
        self.dept_list06 = kwargs.get('hhr_dept_list06', '')
        self.dept_list07 = kwargs.get('hhr_dept_list07', '')
        self.dept_list08 = kwargs.get('hhr_dept_list08', '')
        self.dept_list09 = kwargs.get('hhr_dept_list09', '')
        self.dept_list10 = kwargs.get('hhr_dept_list10', '')
        self.dept_list11 = kwargs.get('hhr_dept_list11', '')
        self.dept_list12 = kwargs.get('hhr_dept_list12', '')
        self.dept_list13 = kwargs.get('hhr_dept_list13', '')
        self.dept_list14 = kwargs.get('hhr_dept_list14', '')
        self.dept_list15 = kwargs.get('hhr_dept_list15', '')
        self.dept_list16 = kwargs.get('hhr_dept_list16', '')
        self.dept_list17 = kwargs.get('hhr_dept_list17', '')
        self.dept_list18 = kwargs.get('hhr_dept_list18', '')
        self.dept_list19 = kwargs.get('hhr_dept_list19', '')
        self.dept_list20 = kwargs.get('hhr_dept_list20', '')
        self.dept_list21 = kwargs.get('hhr_dept_list21', '')
        self.dept_list22 = kwargs.get('hhr_dept_list22', '')
        self.dept_list23 = kwargs.get('hhr_dept_list23', '')
        self.dept_list24 = kwargs.get('hhr_dept_list24', '')
        self.dept_list25 = kwargs.get('hhr_dept_list25', '')
        self.dept_list26 = kwargs.get('hhr_dept_list26', '')
        self.dept_list27 = kwargs.get('hhr_dept_list27', '')
        self.dept_list28 = kwargs.get('hhr_dept_list28', '')
        self.dept_list29 = kwargs.get('hhr_dept_list29', '')
        self.dept_list30 = kwargs.get('hhr_dept_list30', '')

        self.dept_amt01 = kwargs.get('hhr_dept_amt01', 0)
        self.dept_amt02 = kwargs.get('hhr_dept_amt02', 0)
        self.dept_amt03 = kwargs.get('hhr_dept_amt03', 0)
        self.dept_amt04 = kwargs.get('hhr_dept_amt04', 0)
        self.dept_amt05 = kwargs.get('hhr_dept_amt05', 0)
        self.dept_amt06 = kwargs.get('hhr_dept_amt06', 0)
        self.dept_amt07 = kwargs.get('hhr_dept_amt07', 0)
        self.dept_amt08 = kwargs.get('hhr_dept_amt08', 0)
        self.dept_amt09 = kwargs.get('hhr_dept_amt09', 0)
        self.dept_amt10 = kwargs.get('hhr_dept_amt10', 0)
        self.dept_amt11 = kwargs.get('hhr_dept_amt11', 0)
        self.dept_amt12 = kwargs.get('hhr_dept_amt12', 0)
        self.dept_amt13 = kwargs.get('hhr_dept_amt13', 0)
        self.dept_amt14 = kwargs.get('hhr_dept_amt14', 0)
        self.dept_amt15 = kwargs.get('hhr_dept_amt15', 0)

        self.asso_info_attr01 = kwargs.get('hhr_py_org_asso_info_attr01', '')
        self.asso_info_attr02 = kwargs.get('hhr_py_org_asso_info_attr02', '')
        self.asso_info_attr03 = kwargs.get('hhr_py_org_asso_info_attr03', '')
        self.asso_info_attr04 = kwargs.get('hhr_py_org_asso_info_attr04', '')
        self.asso_info_attr05 = kwargs.get('hhr_py_org_asso_info_attr05', '')
        self.asso_info_attr06 = kwargs.get('hhr_py_org_asso_info_attr06', '')
        self.asso_info_attr07 = kwargs.get('hhr_py_org_asso_info_attr07', '')
        self.asso_info_attr08 = kwargs.get('hhr_py_org_asso_info_attr08', '')
        self.asso_info_attr09 = kwargs.get('hhr_py_org_asso_info_attr09', '')
        self.asso_info_attr10 = kwargs.get('hhr_py_org_asso_info_attr10', '')
        self.asso_info_attr11 = kwargs.get('hhr_py_org_asso_info_attr11', '')
        self.asso_info_attr12 = kwargs.get('hhr_py_org_asso_info_attr12', '')
        self.asso_info_attr13 = kwargs.get('hhr_py_org_asso_info_attr13', '')
        self.asso_info_attr14 = kwargs.get('hhr_py_org_asso_info_attr14', '')
        self.asso_info_attr15 = kwargs.get('hhr_py_org_asso_info_attr15', '')
