# -*- coding: utf-8 -*-


class PosnAssoc:
    """
    Desc: 岗位关联信息
    Author: David
    Date: 2020/12/11
    """

    def __init__(self, **kwargs):
        self.tenant_id = kwargs.get('tenant_id', 0)
        self.dept_code = kwargs.get('hhr_posn_code', '')
        self.efft_date = kwargs.get('hhr_efft_date', None)
        self.efft_end_date = kwargs.get('hhr_hhr_efft_end_date', None)
        self.pay_method = '' if kwargs.get('hhr_pay_method', '') is None else kwargs.get('hhr_pay_method')
        self.posn_list01 = '' if kwargs.get('hhr_posn_list01', '') is None else kwargs.get('hhr_posn_list01')
        self.posn_list02 = '' if kwargs.get('hhr_posn_list02', '') is None else kwargs.get('hhr_posn_list02')
        self.posn_list03 = '' if kwargs.get('hhr_posn_list03', '') is None else kwargs.get('hhr_posn_list03')
        self.posn_list04 = '' if kwargs.get('hhr_posn_list04', '') is None else kwargs.get('hhr_posn_list04')
        self.posn_list05 = '' if kwargs.get('hhr_posn_list05', '') is None else kwargs.get('hhr_posn_list05')
        self.posn_list06 = '' if kwargs.get('hhr_posn_list06', '') is None else kwargs.get('hhr_posn_list06')
        self.posn_list07 = '' if kwargs.get('hhr_posn_list07', '') is None else kwargs.get('hhr_posn_list07')
        self.posn_list08 = '' if kwargs.get('hhr_posn_list08', '') is None else kwargs.get('hhr_posn_list08')
        self.posn_list09 = '' if kwargs.get('hhr_posn_list09', '') is None else kwargs.get('hhr_posn_list09')
        self.posn_list10 = '' if kwargs.get('hhr_posn_list10', '') is None else kwargs.get('hhr_posn_list10')
        self.posn_list11 = '' if kwargs.get('hhr_posn_list11', '') is None else kwargs.get('hhr_posn_list11')
        self.posn_list12 = '' if kwargs.get('hhr_posn_list12', '') is None else kwargs.get('hhr_posn_list12')
        self.posn_list13 = '' if kwargs.get('hhr_posn_list13', '') is None else kwargs.get('hhr_posn_list13')
        self.posn_list14 = '' if kwargs.get('hhr_posn_list14', '') is None else kwargs.get('hhr_posn_list14')
        self.posn_list15 = '' if kwargs.get('hhr_posn_list15', '') is None else kwargs.get('hhr_posn_list15')
        self.posn_list16 = '' if kwargs.get('hhr_posn_list16', '') is None else kwargs.get('hhr_posn_list16')
        self.posn_list17 = '' if kwargs.get('hhr_posn_list17', '') is None else kwargs.get('hhr_posn_list17')
        self.posn_list18 = '' if kwargs.get('hhr_posn_list18', '') is None else kwargs.get('hhr_posn_list18')
        self.posn_list19 = '' if kwargs.get('hhr_posn_list19', '') is None else kwargs.get('hhr_posn_list19')
        self.posn_list20 = '' if kwargs.get('hhr_posn_list20', '') is None else kwargs.get('hhr_posn_list20')
        self.posn_list21 = '' if kwargs.get('hhr_posn_list21', '') is None else kwargs.get('hhr_posn_list21')
        self.posn_list22 = '' if kwargs.get('hhr_posn_list22', '') is None else kwargs.get('hhr_posn_list22')
        self.posn_list23 = '' if kwargs.get('hhr_posn_list23', '') is None else kwargs.get('hhr_posn_list23')
        self.posn_list24 = '' if kwargs.get('hhr_posn_list24', '') is None else kwargs.get('hhr_posn_list24')
        self.posn_list25 = '' if kwargs.get('hhr_posn_list25', '') is None else kwargs.get('hhr_posn_list25')
        self.posn_list26 = '' if kwargs.get('hhr_posn_list26', '') is None else kwargs.get('hhr_posn_list26')
        self.posn_list27 = '' if kwargs.get('hhr_posn_list27', '') is None else kwargs.get('hhr_posn_list27')
        self.posn_list28 = '' if kwargs.get('hhr_posn_list28', '') is None else kwargs.get('hhr_posn_list28')
        self.posn_list29 = '' if kwargs.get('hhr_posn_list29', '') is None else kwargs.get('hhr_posn_list29')
        self.posn_list30 = '' if kwargs.get('hhr_posn_list30', '') is None else kwargs.get('hhr_posn_list30')
        self.posn_list31 = '' if kwargs.get('hhr_posn_list31', '') is None else kwargs.get('hhr_posn_list31')
        self.posn_list32 = '' if kwargs.get('hhr_posn_list32', '') is None else kwargs.get('hhr_posn_list32')
        self.posn_list33 = '' if kwargs.get('hhr_posn_list33', '') is None else kwargs.get('hhr_posn_list33')
        self.posn_list34 = '' if kwargs.get('hhr_posn_list34', '') is None else kwargs.get('hhr_posn_list34')
        self.posn_list35 = '' if kwargs.get('hhr_posn_list35', '') is None else kwargs.get('hhr_posn_list35')
        self.posn_list36 = '' if kwargs.get('hhr_posn_list36', '') is None else kwargs.get('hhr_posn_list36')
        self.posn_list37 = '' if kwargs.get('hhr_posn_list37', '') is None else kwargs.get('hhr_posn_list37')
        self.posn_list38 = '' if kwargs.get('hhr_posn_list38', '') is None else kwargs.get('hhr_posn_list38')
        self.posn_list39 = '' if kwargs.get('hhr_posn_list39', '') is None else kwargs.get('hhr_posn_list39')
        self.posn_list40 = '' if kwargs.get('hhr_posn_list40', '') is None else kwargs.get('hhr_posn_list40')
        self.posn_list41 = '' if kwargs.get('hhr_posn_list41', '') is None else kwargs.get('hhr_posn_list41')
        self.posn_list42 = '' if kwargs.get('hhr_posn_list42', '') is None else kwargs.get('hhr_posn_list42')
        self.posn_list43 = '' if kwargs.get('hhr_posn_list43', '') is None else kwargs.get('hhr_posn_list43')
        self.posn_list44 = '' if kwargs.get('hhr_posn_list44', '') is None else kwargs.get('hhr_posn_list44')
        self.posn_list45 = '' if kwargs.get('hhr_posn_list45', '') is None else kwargs.get('hhr_posn_list45')
        self.posn_list46 = '' if kwargs.get('hhr_posn_list46', '') is None else kwargs.get('hhr_posn_list46')
        self.posn_list47 = '' if kwargs.get('hhr_posn_list47', '') is None else kwargs.get('hhr_posn_list47')
        self.posn_list48 = '' if kwargs.get('hhr_posn_list48', '') is None else kwargs.get('hhr_posn_list48')
        self.posn_list49 = '' if kwargs.get('hhr_posn_list49', '') is None else kwargs.get('hhr_posn_list49')
        self.posn_list50 = '' if kwargs.get('hhr_posn_list50', '') is None else kwargs.get('hhr_posn_list50')
        self.posn_list51 = '' if kwargs.get('hhr_posn_list51', '') is None else kwargs.get('hhr_posn_list51')
        self.posn_list52 = '' if kwargs.get('hhr_posn_list52', '') is None else kwargs.get('hhr_posn_list52')
        self.posn_list53 = '' if kwargs.get('hhr_posn_list53', '') is None else kwargs.get('hhr_posn_list53')
        self.posn_list54 = '' if kwargs.get('hhr_posn_list54', '') is None else kwargs.get('hhr_posn_list54')
        self.posn_list55 = '' if kwargs.get('hhr_posn_list55', '') is None else kwargs.get('hhr_posn_list55')
        self.posn_list56 = '' if kwargs.get('hhr_posn_list56', '') is None else kwargs.get('hhr_posn_list56')
        self.posn_list57 = '' if kwargs.get('hhr_posn_list57', '') is None else kwargs.get('hhr_posn_list57')
        self.posn_list58 = '' if kwargs.get('hhr_posn_list58', '') is None else kwargs.get('hhr_posn_list58')
        self.posn_list59 = '' if kwargs.get('hhr_posn_list59', '') is None else kwargs.get('hhr_posn_list59')
        self.posn_list60 = '' if kwargs.get('hhr_posn_list60', '') is None else kwargs.get('hhr_posn_list60')

        self.posn_amt01 = 0 if kwargs.get('hhr_posn_amt01', 0) is None else kwargs.get('hhr_posn_amt01')
        self.posn_amt02 = 0 if kwargs.get('hhr_posn_amt02', 0) is None else kwargs.get('hhr_posn_amt02')
        self.posn_amt03 = 0 if kwargs.get('hhr_posn_amt03', 0) is None else kwargs.get('hhr_posn_amt03')
        self.posn_amt04 = 0 if kwargs.get('hhr_posn_amt04', 0) is None else kwargs.get('hhr_posn_amt04')
        self.posn_amt05 = 0 if kwargs.get('hhr_posn_amt05', 0) is None else kwargs.get('hhr_posn_amt05')
        self.posn_amt06 = 0 if kwargs.get('hhr_posn_amt06', 0) is None else kwargs.get('hhr_posn_amt06')
        self.posn_amt07 = 0 if kwargs.get('hhr_posn_amt07', 0) is None else kwargs.get('hhr_posn_amt07')
        self.posn_amt08 = 0 if kwargs.get('hhr_posn_amt08', 0) is None else kwargs.get('hhr_posn_amt08')
        self.posn_amt09 = 0 if kwargs.get('hhr_posn_amt09', 0) is None else kwargs.get('hhr_posn_amt09')
        self.posn_amt10 = 0 if kwargs.get('hhr_posn_amt10', 0) is None else kwargs.get('hhr_posn_amt10')
        self.posn_amt11 = 0 if kwargs.get('hhr_posn_amt11', 0) is None else kwargs.get('hhr_posn_amt11')
        self.posn_amt12 = 0 if kwargs.get('hhr_posn_amt12', 0) is None else kwargs.get('hhr_posn_amt12')
        self.posn_amt13 = 0 if kwargs.get('hhr_posn_amt13', 0) is None else kwargs.get('hhr_posn_amt13')
        self.posn_amt14 = 0 if kwargs.get('hhr_posn_amt14', 0) is None else kwargs.get('hhr_posn_amt14')
        self.posn_amt15 = 0 if kwargs.get('hhr_posn_amt15', 0) is None else kwargs.get('hhr_posn_amt15')
        self.posn_amt16 = 0 if kwargs.get('hhr_posn_amt16', 0) is None else kwargs.get('hhr_posn_amt16')
        self.posn_amt17 = 0 if kwargs.get('hhr_posn_amt17', 0) is None else kwargs.get('hhr_posn_amt17')
        self.posn_amt18 = 0 if kwargs.get('hhr_posn_amt18', 0) is None else kwargs.get('hhr_posn_amt18')
        self.posn_amt19 = 0 if kwargs.get('hhr_posn_amt19', 0) is None else kwargs.get('hhr_posn_amt19')
        self.posn_amt20 = 0 if kwargs.get('hhr_posn_amt20', 0) is None else kwargs.get('hhr_posn_amt20')
        self.posn_amt21 = 0 if kwargs.get('hhr_posn_amt21', 0) is None else kwargs.get('hhr_posn_amt21')
        self.posn_amt22 = 0 if kwargs.get('hhr_posn_amt22', 0) is None else kwargs.get('hhr_posn_amt22')
        self.posn_amt23 = 0 if kwargs.get('hhr_posn_amt23', 0) is None else kwargs.get('hhr_posn_amt23')
        self.posn_amt24 = 0 if kwargs.get('hhr_posn_amt24', 0) is None else kwargs.get('hhr_posn_amt24')
        self.posn_amt25 = 0 if kwargs.get('hhr_posn_amt25', 0) is None else kwargs.get('hhr_posn_amt25')
        self.posn_amt26 = 0 if kwargs.get('hhr_posn_amt26', 0) is None else kwargs.get('hhr_posn_amt26')
        self.posn_amt27 = 0 if kwargs.get('hhr_posn_amt27', 0) is None else kwargs.get('hhr_posn_amt27')
        self.posn_amt28 = 0 if kwargs.get('hhr_posn_amt28', 0) is None else kwargs.get('hhr_posn_amt28')
        self.posn_amt29 = 0 if kwargs.get('hhr_posn_amt29', 0) is None else kwargs.get('hhr_posn_amt29')
        self.posn_amt30 = 0 if kwargs.get('hhr_posn_amt30', 0) is None else kwargs.get('hhr_posn_amt30')

        self.asso_info_attr01 = '' if kwargs.get('hhr_py_posn_asso_info_attr01', '') is None else kwargs.get('hhr_py_posn_asso_info_attr01')

        self.asso_info_attr02 = '' if kwargs.get('hhr_py_posn_asso_info_attr02', '') is None else kwargs.get('hhr_py_posn_asso_info_attr02')
        self.asso_info_attr03 = '' if kwargs.get('hhr_py_posn_asso_info_attr03', '') is None else kwargs.get('hhr_py_posn_asso_info_attr03')
        self.asso_info_attr04 = '' if kwargs.get('hhr_py_posn_asso_info_attr04', '') is None else kwargs.get('hhr_py_posn_asso_info_attr04')
        self.asso_info_attr05 = '' if kwargs.get('hhr_py_posn_asso_info_attr05', '') is None else kwargs.get('hhr_py_posn_asso_info_attr05')
        self.asso_info_attr06 = '' if kwargs.get('hhr_py_posn_asso_info_attr06', '') is None else kwargs.get('hhr_py_posn_asso_info_attr06')
        self.asso_info_attr07 = '' if kwargs.get('hhr_py_posn_asso_info_attr07', '') is None else kwargs.get('hhr_py_posn_asso_info_attr07')
        self.asso_info_attr08 = '' if kwargs.get('hhr_py_posn_asso_info_attr08', '') is None else kwargs.get('hhr_py_posn_asso_info_attr08')
        self.asso_info_attr09 = '' if kwargs.get('hhr_py_posn_asso_info_attr09', '') is None else kwargs.get('hhr_py_posn_asso_info_attr09')
        self.asso_info_attr10 = '' if kwargs.get('hhr_py_posn_asso_info_attr10', '') is None else kwargs.get('hhr_py_posn_asso_info_attr10')
        self.asso_info_attr11 = '' if kwargs.get('hhr_py_posn_asso_info_attr11', '') is None else kwargs.get('hhr_py_posn_asso_info_attr11')
        self.asso_info_attr12 = '' if kwargs.get('hhr_py_posn_asso_info_attr12', '') is None else kwargs.get('hhr_py_posn_asso_info_attr12')
        self.asso_info_attr13 = '' if kwargs.get('hhr_py_posn_asso_info_attr13', '') is None else kwargs.get('hhr_py_posn_asso_info_attr13')
        self.asso_info_attr14 = '' if kwargs.get('hhr_py_posn_asso_info_attr14', '') is None else kwargs.get('hhr_py_posn_asso_info_attr14')
        self.asso_info_attr15 = '' if kwargs.get('hhr_py_posn_asso_info_attr15', '') is None else kwargs.get('hhr_py_posn_asso_info_attr15')
